# Silaty
# Copyright (c) 2018 - 2019 AXeL
# Copyright (c) 2014 - 2015 Jessewb786

language = 'English'

def set_language(lang):
	global language
	language = lang

def translate_text(text):
	#print ("DEBUG: translate text '%s' in '%s'" % (text, language))
	arabicTranslations = {
		'Silaty': 'صلاتي',
		'Fajr': 'الفجر',
		'Shuruk': 'الشروق',
		'Dhuhr': 'الظهر',
		'Asr': 'العصر',
		'Maghrib': 'المغرب',
		'Isha': 'العشاء',
		'System': 'إعدادات التطبيق',
		'Start Minimized:': 'إخفاء نافذة التطبيق عند بدء التشغيل:',
		'Daylight Saving Time:': 'تفعيل التوقيت الصيفي:',
		'Clock Format:': 'تنسيق الساعة:',
		'12h': '12 ساعة',
		'24h': '24 ساعة',
		'Adjust Hijri Calendar:': 'ضبط التقويم الهجري:',
		'Language:': 'اللغة:',
		'English': 'الإنجليزية',
		'French': 'الفرنسية',
		'Arabic': 'العربية',
		'Notifications': 'الإشعارات',
		'Show Time left with Icon:': 'عرض الوقت المتبقي بجانب الأيقونة:',
		'Enable audio notifications:': 'تفعيل الإشعارات الصوتية:',
		'Time before notification:': 'الوقت قبل الإشعار:',
		'Fajr Adhan:': 'أذان الفجر:',
		'Normal Adhan:': 'أذان عادي:',
		'Jurisprudence': 'الفقه',
		'Calculation Method:': 'طريقة الحساب:',
		'Makkah': 'مكة المكرمة',
		'Egypt': 'مصر',
		'Karachi': 'كراتشي',
		'ISNA': 'الجمعية الإسلامية لأمريكا الشمالية',
		'MWL': 'رابطة العالم الإسلامي',
		'Madhab:': 'المذهب:',
		'Hanafi': 'حنفي',
		'Default': 'افتراضي',
		'Location': 'الموقع',
		'City:': 'المدينة:',
		'Latitude:': 'خط العرض:',
		'Longitude:': 'خط الطول:',
		'Time Zone:': 'التوقيت الزمني:',
		'Location: %s': 'الموقع: %s',
		'Qibla is %.2f° from True North': 'القبلة على بعد %.2f درجة من الشمال الحقيقي',
		'Fajr\t\t\t\t\t%s': 'الفجر\t\t\t\t\t%s',
		'Shuruk\t\t\t\t%s': 'الشروق\t\t\t\t%s',
		'Dhuhr\t\t\t\t\t%s': 'الظهر\t\t\t\t\t%s',
		'Asr\t\t\t\t\t%s': 'العصر\t\t\t\t\t%s',
		'Maghrib\t\t\t\t%s': 'المغرب\t\t\t\t\t%s',
		'Isha\t\t\t\t\t%s': 'العشاء\t\t\t\t\t%s',
		'Next Prayer': 'الصلاة التالية',
		'About': 'حول التطبيق',
		'Settings': 'الإعدادات',
		'Quit': 'خروج',
		'%s until %s': '%s حتى صلاة %s',
		'%s in %s': '%s بعد %s',
		'%s Hours': '%s ساعة',
		'%s Minutes': '%s دقيقة',
		'%s Hours and %s Minutes': '%s ساعة و %s دقيقة',
		'%shr': '%s ساعة',
		'%smin': '%s دقيقة',
		'%shr %smin': '%s ساعة %s دقيقة',
		'GitHub Project Page': 'صفحة المشروع على GitHub',
		'A neat Prayer Time Reminder App.\n Simple and complete so no prayer is missed': 'تطبيق أوقات الصلاة.\n بسيط و شامل حتى لا تفوتك أي صلاة',
		'Copyright © %s Silaty Team': 'حقوق النشر محفوظة © %s فريق صلاتي',
		'Silaty needs to be restarted, restart now?': 'يحتاج التطبيق إلى إعادة تشغيل، إعادة التشغيل الآن؟',
		'Hijri:': 'هجري:',
		'Sunday': 'الأحد',
		'Monday': 'الإثنين',
		'Tuesday': 'الثلاثاء',
		'Wednesday': 'الأربعاء',
		'Thursday': 'الخميس',
		'Friday': 'الجمعة',
		'Saturday': 'السبت',
		'SundayShort': 'ح',
		'MondayShort': 'ن',
		'TuesdayShort': 'ث',
		'WednesdayShort': 'ر',
		'ThursdayShort': 'خ',
		'FridayShort': 'ج',
		'SaturdayShort': 'س',
		'January': 'يناير',
		'February': 'فبراير',
		'March': 'مارس',
		'April': 'أبريل',
		'May': 'مايو',
		'June': 'يونيو',
		'July': 'يوليو',
		'August': 'أغسطس',
		'September': 'سبتمبر',
		'October': 'أكتوبر',
		'November': 'نوفمبر',
		'December': 'ديسمبر',
		'Muharram': 'محرم',
		'Safar': 'صفر',
		'Rabi al Awwal': 'ربيع الأول',
		'Rabi al Akhira': 'ربيع الآخر',
		'Jumada al Ula': 'جمادى الأولى',
		'Jumada al Akhira': 'جمادى الآخرة',
		'Rajab': 'رجب',
		'Sha\'ban': 'شعبان',
		'Ramadhan': 'رمضان',
		'Shawwal': 'شوال',
		'Dhu al Qa\'da': 'ذو القعدة',
		'Dhu al Hijja': 'ذو الحجة',
		'Qibla direction :': 'اتجاه القبلة :',
		'Country : %s': 'الدولة : %s',
		'City : %s': 'المدينة : %s',
		'Search:': 'بحث:',
		'Check your location on %s': 'يمكنك التحقق من موقعك على %s',
		'Get Ready': 'إستعد',
		'%s minutes left until the %s prayer.': '%s دقائق متبقية حتى صلاة %s.',
		'Prayer time for %s': 'وقت صلاة %s',
		'It\'s time for the %s prayer.': 'حان الوقت لصلاة %s.',
		'%s, %s': '%s، %s',
		'%s - %s, %s / %s': '%s - %s، %s / %s',
		'AM': 'ص',
		'PM': 'م',
	}
	frenchTranslations = {
		'Silaty': 'Silaty',
		# TODO: complete french translation
	}
	englishWeekDays = {
		'SundayShort': 'S',
		'MondayShort': 'M',
		'TuesdayShort': 'T',
		'WednesdayShort': 'W',
		'ThursdayShort': 'T',
		'FridayShort': 'F',
		'SaturdayShort': 'S',
	}

	if language == 'Arabic' and text in arabicTranslations:
		return arabicTranslations[text]
	elif language == 'French' and text in frenchTranslations:
		return frenchTranslations[text]
	elif text in englishWeekDays:
		return englishWeekDays[text]
	else:
		return text
